config/routes.rb
BooksApp::Application.routes.draw do
  resources :authors do 
    resources :books do
      resources :words
    end
  end

  root :to => 'authors#index' 
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name, :books

  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :author_id, :words

  belongs_to :author
  has_and_belongs_to_many :words
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :word, :books

  has_and_belongs_to_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all

    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])

    @books = @author.books

    @book = Book.new
  end

  def create
    @author = Author.create(params[:author])

    redirect_to root_path
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path    
  end

  def edit
    @author = Author.find(params[:id])    
  end

  def update
    @author = Author.update(params[:id], params[:name])

    redirect_to root_path    
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @author = Author.find(params[:author_id])

    @author.books << @book
    @words = @book.words

    @word = Word.new
  end

  def create
    @book = Book.create(params[:title])

    @author = Author.find(params[:author_id])

    author_path(@book.author_id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    author_path(@book.author_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.update(params[:id], params[:title])    
    @author = Author.find(params[:author_id])

    author_path(@book.author_id)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def create
    @word = Word.create(params[:word])
    @book = Book.find(params[:book_id])

    @book.words << @word
    redirect_to author_book_path(@book.id)
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to author_book_path(@book.id)
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.update(params[:id], params[:word])
    redirect_to author_book_path(@book.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/authors/edit.html.erb
<h1>Edit</h1>

<%= form_for @author do |f| %>
	<%= f.text_field :name %>
	<%= f.submit('edit') %>
<% end %>

<%= link_to "delete", {:controller => :authors,
      :action => 'destroy', :id => @author.id }, :method => :delete %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<% @authors.each do |author| %>
	<a href='/authors/<%= author.id %>' ><p><%= author.name %></p></a>
<% end %>

<%= form_for @author do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<% if @books.present? %>
	<% @books.each do |book| %>
		<a href='/authors/<%= @author.id %>/books/<%= book.id %>'><p><%= book.title %></p></a>
	<% end %>
<% end %>

<%= link_to "edit", edit_author_path(@author) %>

<%= form_for @book, "/authors/#{@author.id}/books", :method => :post do |f| %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %> 

app/views/books/edit.html.erb
<h1>Edit</h1>

<%= form_for @book do |f| %>
	<%= f.text_field :title %>
	<%= f.submit('edit') %>
<% end %>

<%= link_to "delete", {:controller => :author,
      :action => 'destroy', :id => @book.id }, :method => :delete %>

app/views/books/show.html.erb
<h1><%= @book %></h1>

<% @words.each do |word| %>
	<a href='/authors/<%= @author.id %>/books/<%= @book.id %>/words/<%= word.id %>'><p><%= word.word %></p></a>
<% end %>

<%= link_to "edit", edit_author_book_path(@book) %>

<%= form_for @word do |f| %>
	<%= f.text_field :word %>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooksApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/words/edit.html.erb
<h1>Edit</h1>

<%= form_for @word do |f| %>
	<%= f.text_field :word %>
	<%= f.submit('edit') %>
<% end %>

<%= link_to "delete", {:controller => :author,
      :action => 'destroy', :id => @word.id }, :method => :delete %>

app/views/words/show.html.erb
<h1><%= @ %></h1>

<% @words.each do |word| %>
	<a href='/authors/<%= @author.id %>/books/<%= @book.id %>/words/<%= word.id %>'><p><%= word.word %></p></a>
<% end %>

<%= link_to "edit", edit_author_book_path(@book) %>

<%= form_for @word do |f| %>
	<%= f.text_field :word %>
	<%= f.submit %>
<% end %>